services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-stock-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - /home/mg/mongo-dat:/data/db
    restart: unless-stopped
